name: "Action Helm Datree"
description: "Run the helm datree plugin"
inputs:
  chart_directory:
    description: "Custom chart directory path"
    required: false
    default: "."
  values_file:
    description: "Custom values file path"
    required: false
    default: "values.yaml"
  datree_token: 
    description: "Datree user token"
    required: true
outputs:
  result:
    description: "Result of pass/failures"
runs:
  using: "composite"
  steps:
    - run: |
        export DATREE_TOKEN="${{ inputs.datree_token }}"
        wget https://get.helm.sh/helm-v3.4.1-linux-amd64.tar.gz
        tar xvf helm-v3.4.1-linux-amd64.tar.gz
        chmod +x linux-amd64/helm
        ./linux-amd64/helm plugin install https://github.com/datreeio/helm-datree
        ./linux-amd64/helm datree test ${{ inputs.chart_directory }} -- --values ${{ .inputs.value_file }} > output
        result=$(cat output)
        echo "::set-output name=result::$result"
      shell: bash
