name: "Action Helm Datree"
description: "Run the helm datree plugin"
inputs:
  datree_token: 
    description: "Datree user token"
    required: true
outputs:
  result:
    description: "Result of pass/failures"
runs:
  using: "docker"
  image: "ubuntu:latest"
  args: 
   - ${{ inputs.datree_token }}
