name: "Action Helm Datree"
description: "Run the helm datree plugin"
inputs:
  chart_directory:
    description: "Custom chart directory path"
    required: false
    default: "."
  values_file:
    description: "Custom values file path"
    required: false
    default: "values.yaml"
  datree_token: 
    description: "Datree user token"
    required: true
outputs:
  result:
    description: "Result of pass/failures"
runs:
  using: "composite"
  steps:
    - run: sudo apt install git
      shell: bash
    - run: |
        curl https://baltocdn.com/helm/signing.asc | sudo apt-key add -
        sudo apt-get install apt-transport-https --yes
        echo "deb https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update
        sudo apt-get install helm
      shell: bash
    - run: helm plugin install https://github.com/datreeio/helm-datree
      shell: bash
    - run: |
        export DATREE_TOKEN="${{ inputs.datree_token }}"
        ls ${{ inputs.chart_directory }}
        helm datree test ${{ inputs.chart_directory }} --ignore-missing-schemas -- --values ${{ inputs.chart_directory }}/${{ inputs.values_file }}
        echo "::set-output name=result::$?"
      shell: bash
