name: "Action Helm Datree"
description: "Run the helm datree plugin"
inputs:
  chart_directory:
    description: "Custom chart directory path"
    required: false
    default: "."
  values_file:
    description: "Custom values file path"
    required: false
    default: "values.yaml"
  datree_token: 
    description: "Datree user token"
    required: true
outputs:
  result:
    description: "Result of pass/failures"
runs:
  using: "docker"
  image: "Dockerfile"
  args: 
   - ${{ inputs.datree_token }}
   - ${{ inputs.chart_directory }}
   - ${{ inputs.values_file }}
